### ISSUE TITLE
[BUG] Using the API instead of the .yaml config files changes environment parameters only for the Trainer Worker.

### ISSUE THREAD

**Issue by SinergAIze** [Replicable-MARL/MARLlib#147]
Hello, thanks for MARLlib, it's a fantastic tool!

I believe there is a bug occuring when specifying some configuration parameters via the API method: The `Worker`s only access the `.yaml` configuration file to instantiate the environments on which they compute inferences, rather than the config specified via the API, like `marl.make_env()` for example.

For example, when specifying a different value of the `local_ratio` parameter via `marl.make_env()` for MPE environements, as follows, leads to very similar results.

```python
env = marl.make_env(
    environment_name='mpe',
    map_name='simple_spread',
    force_coop=False,
    # env_params keyword args.
    local_ratio=0.01,
    continuous_actions=False,
    # ...
)
```

However, when completing trainings one at a time and changing the value of the `local_ratio: ...` value in the [`marllib/envs/base_env/config/mpe.yaml`](https://github.com/Replicable-MARL/MARLlib/blob/0ac275e6132e653f826b107e79963a1485bcd425/marllib/envs/base_env/config/mpe.yaml) file, as follows, leads to differing and more logical results!

```yaml
# Custom marllib/envs/base_env/config/mpe.yaml
env: mpe

env_args:
  map_name: "simple_spread" # others can be found in mpe.py
  N: 3
  local_ratio: 0.1 # Change each training run.
  max_cycles: 25
  continuous_actions: False

mask_flag: False
global_state_flag: False
opp_action_in_cc: True
```

I was wondering if this was intentional behaviour, or if the API is not meant to be able to edit the configuration for all workers, but only edit the `Trainer`'s configuration.

If so, this would imply that the only way to ensure consistent parameter sets between inferences by `Worker` cores and model updates by the `Trainer` would be to only use the `.yaml` config files for parameter specification.

I do not know whether this issue only applies to environment parameters or others as well!

Thanks for reading!
